RS/server-failure
apache/apache_bytes
apache/apache_requests
apache/apache_scoreboard-closing
apache/apache_scoreboard-dnslookup
apache/apache_scoreboard-finishing
apache/apache_scoreboard-idle_cleanup
apache/apache_scoreboard-keepalive
apache/apache_scoreboard-logging
apache/apache_scoreboard-open
apache/apache_scoreboard-reading
apache/apache_scoreboard-sending
apache/apache_scoreboard-starting
apache/apache_scoreboard-waiting
cpu-0/cpu-idle
cpu-0/cpu-interrupt
cpu-0/cpu-nice
cpu-0/cpu-softirq
cpu-0/cpu-steal
cpu-0/cpu-system
cpu-0/cpu-user
cpu-0/cpu-wait
cpu-1/cpu-idle
cpu-1/cpu-interrupt
cpu-1/cpu-nice
cpu-1/cpu-softirq
cpu-1/cpu-steal
cpu-1/cpu-system
cpu-1/cpu-user
cpu-1/cpu-wait
cpu-2/cpu-idle
cpu-2/cpu-interrupt
cpu-2/cpu-nice
cpu-2/cpu-softirq
cpu-2/cpu-steal
cpu-2/cpu-system
cpu-2/cpu-user
cpu-2/cpu-wait
cpu-3/cpu-idle
cpu-3/cpu-interrupt
cpu-3/cpu-nice
cpu-3/cpu-softirq
cpu-3/cpu-steal
cpu-3/cpu-system
cpu-3/cpu-user
cpu-3/cpu-wait
df/df-mnt
df/df-root
disk-sda1/disk-disk_merged
disk-sda1/disk-disk_octets
disk-sda1/disk-disk_ops
disk-sda1/disk-disk_time
disk-sda2/disk-disk_merged
disk-sda2/disk-disk_octets
disk-sda2/disk-disk_ops
disk-sda2/disk-disk_time
disk-sda3/disk-disk_merged
disk-sda3/disk-disk_octets
disk-sda3/disk-disk_ops
disk-sda3/disk-disk_time
dns/dns_octets
dns/dns_opcode-Query
dns/dns_qtype-A
dns/dns_qtype-CNAME
dns/dns_qtype-MX
dns/dns_qtype-NS
dns/dns_qtype-PTR
dns/dns_qtype-SOA
dns/dns_qtype-TXT
dns/dns_rcode-FORMERR
dns/dns_rcode-MAX
dns/dns_rcode-NOERROR
dns/dns_rcode-NOTAUTH
dns/dns_rcode-NOTIMPL
dns/dns_rcode-NXDOMAIN
dns/dns_rcode-REFUSED
dns/dns_rcode-SERVFAIL
haproxy-www/haproxy_sessions-server1
haproxy-www/haproxy_sessions-server2
haproxy-www/haproxy_sessions-total
haproxy-www/haproxy_status-server1
haproxy-www/haproxy_status-server2
haproxy-www/haproxy_traffic-server1
haproxy-www/haproxy_traffic-server2
haproxy-www/haproxy_traffic-total
interface/if_errors-eth0
interface/if_octets-eth0
interface/if_packets-eth0
load/load
memory/memory-buffered
memory/memory-cached
memory/memory-free
memory/memory-used
mysql/mysql_commands-admin_commands
mysql/mysql_commands-alter_table
mysql/mysql_commands-create_table
mysql/mysql_commands-delete
mysql/mysql_commands-flush
mysql/mysql_commands-grant
mysql/mysql_commands-insert
mysql/mysql_commands-select
mysql/mysql_commands-set_option
mysql/mysql_commands-show_master_status
mysql/mysql_commands-show_slave_hosts
mysql/mysql_commands-show_status
mysql/mysql_commands-show_variables
mysql/mysql_commands-update
mysql/mysql_commands-update_multi
mysql/mysql_handler-commit
mysql/mysql_handler-prepare
mysql/mysql_handler-read_first
mysql/mysql_handler-read_key
mysql/mysql_handler-read_rnd_next
mysql/mysql_handler-rollback
mysql/mysql_handler-write
mysql/mysql_octets
mysql/mysql_qcache
mysql/mysql_threads
ping/ping-ec2.amazonaws.com
ping/ping-s3.amazonaws.com
ping/ping-sdb.amazonaws.com
ping/ping-sqs.amazonaws.com
ping/ping-www.rightscale.com
processes-alert/ps_count
processes-alert/ps_cputime
processes-alert/ps_pagefaults
processes-alert/ps_rss
processes-collectd/ps_count
processes-collectd/ps_cputime
processes-collectd/ps_pagefaults
processes-collectd/ps_rss
processes-cron/ps_count
processes-cron/ps_cputime
processes-cron/ps_pagefaults
processes-cron/ps_rss
processes-haproxy/ps_count
processes-haproxy/ps_cputime
processes-haproxy/ps_pagefaults
processes-haproxy/ps_rss
processes-httpd.worker/ps_count
processes-httpd.worker/ps_cputime
processes-httpd.worker/ps_pagefaults
processes-httpd.worker/ps_rss
processes-httpd/ps_count
processes-httpd/ps_cputime
processes-httpd/ps_pagefaults
processes-httpd/ps_rss
processes-merb/ps_count
processes-merb/ps_cputime
processes-merb/ps_pagefaults
processes-merb/ps_rss
processes-mongrel_rails/ps_count
processes-mongrel_rails/ps_cputime
processes-mongrel_rails/ps_pagefaults
processes-mongrel_rails/ps_rss
processes-mysqld/ps_count
processes-mysqld/ps_cputime
processes-mysqld/ps_pagefaults
processes-mysqld/ps_rss
processes-sshd/ps_count
processes-sshd/ps_cputime
processes-sshd/ps_pagefaults
processes-sshd/ps_rss
processes-tomcat/ps_count
processes-tomcat/ps_cputime
processes-tomcat/ps_pagefaults
processes-tomcat/ps_rss
processes/ps_state-blocked
processes/ps_state-paging
processes/ps_state-running
processes/ps_state-sleeping
processes/ps_state-stopped
processes/ps_state-zombies
swap/swap-cached
swap/swap-free
swap/swap-used
users/users
